# my global config
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  # evaluation_interval: 15s # By default, evaluate rules every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #  monitor: 'observability-example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
#- 'alert.rules'
# - "first.rules"
# - "second.rules"

# alert
alerting:
#  alertmanagers:
#  - scheme: http
#    static_configs:
#    - targets:
#      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'dotnet-applications'
    # If honor_labels is set to "true", label conflicts are resolved by keeping label
    # values from the scraped data and ignoring the conflicting server-side labels.
    honor_labels: true
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:8889' ]

  - job_name: 'postgres'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'postgres_exporter:9187' ]
