{
 "title": "Asp.Net Core Service Overview",
 "description": "ASP.NET Core application metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "aspnetcore",
  "opentelemetry",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": { "query": "label_values(target_info,job)" } }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_cpu_count{job=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "target_info{job=\"$service\"}",
     "legendFormat": "{{service_version}}"
    }
   ]
  },
  {
   "title": "Loaded assemblies",
   "type": "stat",
   "description": "The number of .NET assemblies that are currently loaded.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_assemblies_count{job=\"$service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Base graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Service response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{job = \"$service\"}[$__rate_interval]))\n/ \nsum(rate(http_server_request_duration_seconds_count{job = \"$service\"}[$__rate_interval])) \nor vector(0)\n\n",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \nsum (\n    rate(\n        http_client_request_duration_seconds_bucket{job=\"$service\"}[$__rate_interval])\n    )\n    by (le, server_address)\n)",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_client_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_client_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_client_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_client_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", net_peer_name=\"$http_client_peer_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Top 10 Requested Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(max_over_time(http_server_request_duration_seconds_count{job=\"$service\",  http_route!=\"\"}[$__rate_interval]), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=\"$service\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", error_type!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "By handlers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS by handlers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(http_route) (\n    increase(http_server_request_duration_seconds_count{job=\"$service\"}[$__rate_interval])  \n)  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response time by handler (0.5q)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(http_route, le) (increase(http_server_request_duration_seconds_bucket{service_name=\"$service\", http_route!~\"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response time by handler (0.9q)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(http_route, le) (increase(http_server_request_duration_seconds_bucket{service_name=\"$service\", http_route!~\"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response time by handler (0.99q)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(http_route, le) (increase(http_server_request_duration_seconds_bucket{service_name=\"$service\", http_route!~\"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance, state) (increase(process_cpu_time_seconds_total{job=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_memory_usage_bytes{job=\"$service\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Process threads count",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(process_threads{job=\"$service\" }[$__rate_interval])",
     "legendFormat": "Threads"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (generation) (\n  increase(process_runtime_dotnet_gc_collections_count_total{job=\"$service\"}[$__rate_interval])\n)",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Heap Generations (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_size_bytes{job=\"$service\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{job=\"$service\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count_total{job=\"$service\"}[$__rate_interval])",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Thread pool threads",
   "type": "timeseries",
   "description": "The number of thread pool threads that currently exist",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(process_runtime_dotnet_thread_pool_threads_count{job=\"$service\"}[$__rate_interval])",
     "legendFormat": "threads count"
    }
   ]
  }
 ]
}