{
 "title": "Postgres Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_database_size_bytes{datname!~\"template0|template1\"},datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "Number of backends currently connected to this database. This is the only column in this view that returns a value reflecting current state; all other columns return the accumulated values since the last reset.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"$database\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "description": "Number of buffers allocated. 1 buffer = 8k",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total[$__interval])",
     "legendFormat": "buffers alloc"
    }
   ]
  },
  {
   "title": "Cache hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=\"$database\"}) / (sum(pg_stat_database_blks_hit{datname=\"$database\"}) + sum(pg_stat_database_blks_read{datname=\"$database\"}))",
     "legendFormat": "cache hit"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "description": "Disk space used by the database",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$database\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(mode) (pg_locks_count{datname=\"$database\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conflicts / Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_deadlocks{datname=\"$database\"}[$__interval]))",
     "legendFormat": "deadlocks"
    },
    {
     "expr": "sum(irate(pg_stat_database_conflicts{datname=\"$database\"}[$__interval]))",
     "legendFormat": "conflicts"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Number of transactions in this database",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=\"$database\"}[$__interval]))",
     "legendFormat": "commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{datname=\"$database\"}[$__interval]))",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Fetched / Returned rows",
   "type": "timeseries",
   "description": "Number of rows by queries in this database",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{datname=\"$database\"}[$__interval])",
     "legendFormat": "fetched"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{datname=\"$database\"}[$__interval])",
     "legendFormat": "returned"
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true
  }
 ]
}